---
sudo: required

language: python

services:
  - docker

before_install:
  - sudo apt-get -qq update
  # Install any version of ansible simply so we can run ansible-galaxy
  - pip install ansible
  - make download-roles

install:
  - pip install tox-travis

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: TOX_ENV=py27-ansible25
      dist: xenial
    - python: 2.7
      env: TOX_ENV=py27-ansible26
      dist: xenial
  #   - python: "3.8-dev"
  #     env: TOX_ENV=py38
  #     dist: xenial
  #     if: branch = master AND type = push
  # allow_failures:
  #   - python: "2.7"
  #     env: TOX_ENV=py27-ansible27
  #     dist: xenial

cache:
  directories:
    - $HOME/.cache/pip
# script: travis_wait 30 tox --develop
script: tox -e $TOX_ENV
