# https://gist.github.com/gnarf/b103e77f37236ca72d8e
:vms:
  dhclient_dnsmasq1:
    :hostname: "dhclient_dnsmasq1"
    :ip: "192.168.33.100"
    :ram: 512
    :cpu: 1
    :box: "debian/stretch64"

  dhclient_dnsmasq2:
    :hostname: "dhclient_dnsmasq2"
    :ip: "192.168.33.101"
    :ram: 512
    :cpu: 1
    :box: "debian/stretch64"

  dhclient1:
    :hostname: "dhclient1"
    :ip: "192.168.33.102"
    :ram: 512
    :cpu: 1
    :box: "debian/stretch64"

:groups:
  dhclient_dnsmasq1:
    - dhclient_dnsmasq1
  dhclient_dnsmasq2:
    - dhclient_dnsmasq2
  dhclient_dnsmasq_servers:
    - dhclient_dnsmasq1
    - dhclient_dnsmasq2
  dhclient1:
    - dhclient1
  servers:
    - dhclient_dnsmasq1
    - dhclient_dnsmasq2
    - dhclient1
  dns_servers:
    - dhclient_dnsmasq1
    - dhclient_dnsmasq2
  dhclient_servers:
    - dhclient1
