FROM {{ item.image }}

# SOURCE: https://github.com/KAMI911/ansible-role-tomcat/blob/a103425a7897fd2ceb014ebb4ee95b3c485b79e3/molecule/default/Dockerfile.j2

RUN /bin/sh -c 'if [ -x "$(command -v apt-get)" ]; then apt-get update && apt-get upgrade -y && apt-get install -y python sudo bash ca-certificates iproute && apt-get clean; fi'
RUN /bin/sh -c 'if [ -x "$(command -v yum)" ]; then yum makecache fast && yum update -y && yum install -y python sudo yum-plugin-ovl bash ipreoute && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; fi'
RUN /bin/sh -c 'if [ -x "$(command -v zypper)" ]; then zypper refresh && zypper update -y && zypper install -y python sudo bash python-xml iproute && zypper clean -a; fi'
RUN /bin/sh -c 'if [ -x "$(command -v apk)" ]; then apk update && apk add --no-cache python sudo bash ca-certificates iproute; fi'
RUN /bin/sh -c 'if [ -x "$(command -v pacman)" ]; then pacman --sync --noconfirm --refresh python2 bash; fi'
RUN /bin/sh -c 'if [ -x "$(command -v dnf)" ]; then dnf makecache && dnf --assumeyes install python sudo python-devel python2-dnf bash iproute && dnf clean all; fi'
RUN /bin/sh -c 'if [ -x "$(command -v emerge)" ]; then emerge --ask n =dev-lang/python-2\* gentoolkit; fi'
